// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pebruwantoro/movie-festival-backend/internal/app/repositories/token (interfaces: RepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/repository.go -package=mocks . RepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/pebruwantoro/movie-festival-backend/internal/app/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateToken mocks base method.
func (m *MockRepositoryInterface) CreateToken(ctx context.Context, request entities.Token) (entities.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", ctx, request)
	ret0, _ := ret[0].(entities.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockRepositoryInterfaceMockRecorder) CreateToken(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateToken), ctx, request)
}

// GetActiveTokenByJWT mocks base method.
func (m *MockRepositoryInterface) GetActiveTokenByJWT(ctx context.Context, jwt string) (entities.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveTokenByJWT", ctx, jwt)
	ret0, _ := ret[0].(entities.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveTokenByJWT indicates an expected call of GetActiveTokenByJWT.
func (mr *MockRepositoryInterfaceMockRecorder) GetActiveTokenByJWT(ctx, jwt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveTokenByJWT", reflect.TypeOf((*MockRepositoryInterface)(nil).GetActiveTokenByJWT), ctx, jwt)
}

// UpdateToken mocks base method.
func (m *MockRepositoryInterface) UpdateToken(ctx context.Context, request entities.Token) (entities.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateToken", ctx, request)
	ret0, _ := ret[0].(entities.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateToken indicates an expected call of UpdateToken.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateToken(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateToken", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateToken), ctx, request)
}
