name: Code Quality Scan

on:
  pull_requests:
  push:
    branches: ["master"]

jobs:
  code-scan:
    steps:
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Linting Test
        run: |
          mkdir -p test-reports
          apk add --no-cache curl
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |
              sh -s -- -b $(go env GOPATH)/bin v1.57.2
          golangci-lint run --issues-exit-code 0 --timeout 10m --out-format checkstyle > ./test-reports/golangci-lint.out

      - name: Unit Test
        env:
          CGO_ENABLED: "1"
        run: |
          go test -coverprofile=test-reports/coverage.out ./internal/...
          go tool cover -func test-reports/coverage.out -o test-reports/coverage.cov