name: Code Quality Scan

on:
  pull_request:
  push:
    branches: ["master"]

jobs:
  deploy:
    name: Code Quality Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Linting Test
        run: |
          mkdir -p test-reports
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |
              sh -s -- -b $(go env GOPATH)/bin
          golangci-lint run --issues-exit-code 0 --timeout 10m --out-format checkstyle > ./test-reports/golangci-lint.out

      - name: Unit Test
        env:
          CGO_ENABLED: "1"
        run: |
          go test -coverprofile=test-reports/coverage.out ./internal/...
          go tool cover -func test-reports/coverage.out -o test-reports/coverage.cov